#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leoplastic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="leoplastic")]
	public partial class LeoplasticDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproducao(producao instance);
    partial void Updateproducao(producao instance);
    partial void Deleteproducao(producao instance);
    #endregion
		
		public LeoplasticDataContext() : 
				base(global::Leoplastic.Properties.Settings.Default.leoplasticConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LeoplasticDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LeoplasticDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LeoplasticDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LeoplasticDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<producao> producao
		{
			get
			{
				return this.GetTable<producao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producao")]
	public partial class producao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _processo;
		
		private string _equipamento;
		
		private string _data_apontamento;
		
		private string _produto;
		
		private string _peso;
		
		private string _inicio_operacao;
		
		private string _termino_operacao;
		
		private string _ordem;
		
		private string _operador;
		
		private string _densidade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnprocessoChanging(string value);
    partial void OnprocessoChanged();
    partial void OnequipamentoChanging(string value);
    partial void OnequipamentoChanged();
    partial void Ondata_apontamentoChanging(string value);
    partial void Ondata_apontamentoChanged();
    partial void OnprodutoChanging(string value);
    partial void OnprodutoChanged();
    partial void OnpesoChanging(string value);
    partial void OnpesoChanged();
    partial void Oninicio_operacaoChanging(string value);
    partial void Oninicio_operacaoChanged();
    partial void Ontermino_operacaoChanging(string value);
    partial void Ontermino_operacaoChanged();
    partial void OnordemChanging(string value);
    partial void OnordemChanged();
    partial void OnoperadorChanging(string value);
    partial void OnoperadorChanged();
    partial void OndensidadeChanging(string value);
    partial void OndensidadeChanged();
    #endregion
		
		public producao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processo", DbType="NChar(30)")]
		public string processo
		{
			get
			{
				return this._processo;
			}
			set
			{
				if ((this._processo != value))
				{
					this.OnprocessoChanging(value);
					this.SendPropertyChanging();
					this._processo = value;
					this.SendPropertyChanged("processo");
					this.OnprocessoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipamento", DbType="NChar(30)")]
		public string equipamento
		{
			get
			{
				return this._equipamento;
			}
			set
			{
				if ((this._equipamento != value))
				{
					this.OnequipamentoChanging(value);
					this.SendPropertyChanging();
					this._equipamento = value;
					this.SendPropertyChanged("equipamento");
					this.OnequipamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_apontamento", DbType="NChar(30)")]
		public string data_apontamento
		{
			get
			{
				return this._data_apontamento;
			}
			set
			{
				if ((this._data_apontamento != value))
				{
					this.Ondata_apontamentoChanging(value);
					this.SendPropertyChanging();
					this._data_apontamento = value;
					this.SendPropertyChanged("data_apontamento");
					this.Ondata_apontamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produto", DbType="NChar(30)")]
		public string produto
		{
			get
			{
				return this._produto;
			}
			set
			{
				if ((this._produto != value))
				{
					this.OnprodutoChanging(value);
					this.SendPropertyChanging();
					this._produto = value;
					this.SendPropertyChanged("produto");
					this.OnprodutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="NChar(10)")]
		public string peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inicio_operacao", DbType="NChar(30)")]
		public string inicio_operacao
		{
			get
			{
				return this._inicio_operacao;
			}
			set
			{
				if ((this._inicio_operacao != value))
				{
					this.Oninicio_operacaoChanging(value);
					this.SendPropertyChanging();
					this._inicio_operacao = value;
					this.SendPropertyChanged("inicio_operacao");
					this.Oninicio_operacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termino_operacao", DbType="NChar(30)")]
		public string termino_operacao
		{
			get
			{
				return this._termino_operacao;
			}
			set
			{
				if ((this._termino_operacao != value))
				{
					this.Ontermino_operacaoChanging(value);
					this.SendPropertyChanging();
					this._termino_operacao = value;
					this.SendPropertyChanged("termino_operacao");
					this.Ontermino_operacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordem", CanBeNull=false)]
		public string ordem
		{
			get
			{
				return this._ordem;
			}
			set
			{
				if ((this._ordem != value))
				{
					this.OnordemChanging(value);
					this.SendPropertyChanging();
					this._ordem = value;
					this.SendPropertyChanged("ordem");
					this.OnordemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operador", CanBeNull=false)]
		public string operador
		{
			get
			{
				return this._operador;
			}
			set
			{
				if ((this._operador != value))
				{
					this.OnoperadorChanging(value);
					this.SendPropertyChanging();
					this._operador = value;
					this.SendPropertyChanged("operador");
					this.OnoperadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_densidade", CanBeNull=false)]
		public string densidade
		{
			get
			{
				return this._densidade;
			}
			set
			{
				if ((this._densidade != value))
				{
					this.OndensidadeChanging(value);
					this.SendPropertyChanging();
					this._densidade = value;
					this.SendPropertyChanged("densidade");
					this.OndensidadeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
