<?xml version="1.0" encoding="utf-8"?><Database Name="leoplastic" Class="LeoplasticDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;C:\Users\Daniel Mota\Documents\GitHub\Leoplastic\leoplastic.mdf&quot;;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Leoplastic.Properties.Settings" SettingsPropertyName="leoplasticConnectionString" Provider="System.Data.SqlClient" />
</Database>